### ISSUE TITLE
Recommendations for Plotting

### ISSUE THREAD

**Issue by shadowstriker15** [mljs/hclust#12]
Hey guys,

First off just wanted to say that I'm very appreciative of the existence of this library. I have a quick question that is somewhat relevant to this repository. I was wondering if you guys have any recommendations for libraries to plot this data? I have been looking at using d3's dendrogram but I was curious to see if there is something else that I may be missing. Thanks.

**Comment by targos** [comment]
Hello, I always use d3 to plot dendrograms.

**Comment by targos** [comment]
You can see an example in this repository: https://github.com/zakodium/react-heatmap

**Comment by shadowstriker15** [comment]
@targos Thank you for the reference, that's pretty similar to what I was looking for!
