### ISSUE TITLE
working simple example

### ISSUE THREAD

**Issue by trebor** [mljs/hclust#15]
i'm a super new to ml and clustering but i love the simple clean look of what you all have going on here.  the doc is a little thin at the moment.  would it be possible to provide a **super** simple working example in something like [observable](https://observablehq.com/) or [codepen](https://codepen.io)?  i'm learning a lot at once. :)

**Comment by trebor** [comment]
i just found: 
 
   https://github.com/mljs/hclust/blob/master/experiment.js

if that is a proper use example then i might be all set.

**Comment by lpatiny** [comment]
yes it is a good example of the use of the library if you have a distance matrix.
