### ISSUE TITLE
Clustering with distance matrix

### ISSUE THREAD

**Issue by andcastillo** [mljs/hclust#4]
It is necessary that all the methods accepts a distance matrix as input. Sometimes the standar distance metrics are not enough.

**Comment by andcastillo** [comment]
I've modified the agnes to work with a distance matrix, which makes the algorithm more general, and also improves the performance, because all the distances have to be compute only once. Also there was a problem with the current agnes implementation. I've fixed it because the output of the test case should be like this: 
![screen shot 2016-08-12 at 11 38 27 am](https://cloud.githubusercontent.com/assets/3810292/17629807/fdd36d2e-6081-11e6-859a-b2af31e7df37.png)

**Comment by targos** [comment]
can you please open a pull request for those changes ?

**Comment by andcastillo** [comment]
Sorry, I already make a commit. Nevertheless, I did not introduced any breaking change in the package, because I just created a new file agnesDistance. Should I revert and make the pull request? Because the idea would be to make a version 2 of the library, by using the same strategy in the other methods, and let specify in the options if the input is an array of data or a distance matrix.

**Comment by targos** [comment]
No problem. The point is that every non-trivial change should be reviewed by somebody else before going in to the master branch. The PR allows to do that and have a discussion around the code.
